### ISSUE TITLE
`gingado.utils.Lag` does not fit when `keep_contemporaneous_X=True` 

### ISSUE THREAD

**Issue by dkgaraujo** [bis-med-it/gingado#27]
```
import numpy as np
from gingado.utils import Lag
from sklearn.pipeline import Pipeline


X = np.random.rand(15, 2)
y = np.random.rand(15)

lags = 3
jump = 2

pipe = Pipeline([('lagger', Lag(lags=lags, jump=jump, keep_contemporaneous_X=False))]).fit_transform(X, y)
# the above works well, but:
pipe = Pipeline([('lagger', Lag(lags=lags, jump=jump, keep_contemporaneous_X=True))]).fit_transform(X, y)
"""
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib64/python3.11/site-packages/sklearn/base.py", line 1473, in wrapper
      return fit_method(estimator, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib64/python3.11/site-packages/sklearn/pipeline.py", line 544, in fit_transform
      return last_step.fit_transform(
             ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib64/python3.11/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
      data_to_wrap = f(self, X, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib64/python3.11/site-packages/sklearn/base.py", line 1101, in fit_transform
      return self.fit(X, y, **fit_params).transform(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib64/python3.11/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
      data_to_wrap = f(self, X, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/douglas-araujo/.local/lib/python3.11/site-packages/gingado/utils.py", line 90, in transform
      X_colnames = list(self.feature_names_in_) if self.keep_contemporaneous_X else []
                        ^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'Lag' object has no attribute 'feature_names_in_'
"""
```

**Comment by jdamp-bis** [comment]
Scikit-learn is currently refactoring the methods responsible for validation of data, including setting of attributes like `feature_names_in_`. See the changelog for the next feature release 1.6: https://scikit-learn.org/dev/whats_new/v1.6.html
It may be best to fix this once the new functionality is available.

**Comment by jdamp-bis** [comment]
@dkgaraujo 
What is the desired behavior when setting `keep_contemporaneous_X=True` if the input is an array? In particular, which features names are desired for the output DataFrame?

**Comment by dkgaraujo** [comment]
Thank you @jdamp-bis. There is no need to retain column names if the input is an array. Also, to make sure this failure does not happen, we can move the following lines to within the following if statement:

```
X_colnames = list(self.feature_names_in_) if self.keep_contemporaneous_X else []
for lag in range(self.effective_lags_):
    if lag < self.jump:
        continue
    lag_count = lag+1
    lag_X = np.roll(X_forlag, lag_count, axis=0)
    X_lags.append(lag_X)
    if hasattr(self, "feature_names_in_"):
        X_colnames = X_colnames + [col+"_lag_"+str(lag+1) for col in list(self.feature_names_in_)]
```
